//======================================
// BALL3 - Ballistic Cannonball
// Generated by CADAC Builder
//======================================

#include "class_hierarchy.hpp"

///////////////////////////////////////////////////////////////////////////////
//Main function
///////////////////////////////////////////////////////////////////////////////
int main()
{
    // Title
    cout << "\n BALL3 - Ballistic Cannonball (Python API Build)\n";

    // Create vehicle object
    Ball ball;

    // Read input file
    ball.vehicle_load_input();

    // Run simulation
    ball.run();

    return 0;
}
